apiVersion: v1
kind: Service
metadata:
  name: adamchat-backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app: adamchat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
